fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\User

    service: # this lines
        mailer: fos_user.mailer.twig_swift # this lines
        
    from_email:
        address: '%env(resolve:MAILER_USER)%'
        sender_name: '%env(resolve:MAILER_USER)%'